chalk-ai/chalk-java

.github/workflows/publish.yml, README.md, build.gradle
- close and release
- bump to test release
=> Add release step from sonatype to maven central

.github/workflows/publish.yml, .github/workflows/test.yml, src/test/java/ai/chalk/client/TestChalkClient.java, src/test/java/ai/chalk/client/e2e/FraudTemplateFeatures.java, src/test/java/ai/chalk/client/e2e/User.java
- use correct release command
- prep e2e test
=> Fix release command and add test to Actions

src/main/java/ai/chalk/models/OnlineQueryParams.java, src/test/java/ai/chalk/client/TestOnlineQueryParams.java
No good reason it wasn't already there :)
=> Add withInputs

src/main/java/ai/chalk/models/OnlineQueryParams.java, src/test/java/ai/chalk/client/TestOnlineQueryParams.java
Add test for `withTag` and simplify method calls in param builder.
=> minor cleanup and test

README.md, build.gradle, src/main/java/ai/chalk/internal/Utils.java, src/main/java/ai/chalk/internal/bytes/BytesProducer.java, src/main/java/ai/chalk/models/OnlineQueryParams.java, src/main/java/ai/chalk/models/OnlineQueryParamsComplete.java, src/test/java/ai/chalk/client/TestOnlineQueryParams.java, src/test/java/ai/chalk/internal/TestUtils.java
This PR takes care of serializing optional params.
=> Add serialization of optional params

README.md, build.gradle, src/main/java/ai/chalk/internal/request/RequestHandler.java, src/test/java/ai/chalk/client/TestChalkClient.java
This fixes 404s from missing deployment type header
=> Add deployment type header

README.md, build.gradle, src/main/java/ai/chalk/client/ChalkClientImpl.java, src/test/java/ai/chalk/client/TestChalkClient.java
- fix branch not set correctly
- add branch tests
=> Fix branch not set correctly

README.md, build.gradle, src/main/java/ai/chalk/features/Versioned.java, src/main/java/ai/chalk/internal/arrow/Unmarshaller.java, src/main/java/ai/chalk/internal/codegen/Initializer.java, src/test/java/ai/chalk/arrow/TestUnmarshaller.java, src/test/java/ai/chalk/arrow/test_features/ArrowFeatures.java, src/test/java/ai/chalk/arrow/test_features/VersionedFeaturesClass.java, src/test/java/ai/chalk/internal/TestConfigLoader.java
This PR adds a annotation that is used to determine whether a feature is versioned, and hence we can augment the object `Features.user.versioned_feature_v2` to have the FQN `"user.versioned_feature@2"`
=> handle versioned features for codegen [CHA-3409]

src/test/java/ai/chalk/client/TestChalkClient.java
Enable them now that they work
=> Enable branch query test

README.md
Add another way of creating grpc client to readme.
=> More gRPC readme

src/main/java/ai/chalk/client/BuilderImpl.java, src/main/java/ai/chalk/client/ChalkClient.java, src/main/java/ai/chalk/client/ChalkClientImpl.java, src/main/java/ai/chalk/client/GRPCClient.java, src/main/java/ai/chalk/internal/request/RequestHandler.java
Add the `.withQueryServer()` builder method to the ChalkClient builder
=> Add `.withQueryServer()`

README.md, gradle.properties
=> [generated] Release 1.0.5

README.md, gradle.properties
=> [generated] Release 1.0.6

src/main/java/ai/chalk/client/BuilderImpl.java, src/main/java/ai/chalk/client/ChalkClient.java, src/main/java/ai/chalk/client/ChalkClientImpl.java, src/main/java/ai/chalk/client/GRPCClient.java, src/main/java/ai/chalk/client/TokenRefresher.java, src/main/java/ai/chalk/internal/request/RequestHandler.java, src/main/java/ai/chalk/internal/request/models/SendRequestParams.java, src/main/java/ai/chalk/models/OnlineQueryParams.java, src/main/java/ai/chalk/models/OnlineQueryParamsComplete.java, src/main/java/ai/chalk/models/UploadFeaturesParams.java, src/test/java/ai/chalk/client/TestAllClients.java
Adds a timeout param at both the request and client level.
=> Add timeout param

README.md, gradle.properties
=> [generated] Release 1.1.0

src/main/java/ai/chalk/internal/arrow/Unmarshaller.java, src/test/java/ai/chalk/arrow/TestUnmarshaller.java, src/test/java/ai/chalk/arrow/test_features/ArrowUser.java, src/test/java/ai/chalk/arrow/test_features/NestedMapDataclass.java
Handle arrow map types in the Unmarshaller
=> Handle map types in deser

README.md, gradle.properties
=> [generated] Release 1.1.1

src/main/java/ai/chalk/client/ChalkClientImpl.java, src/main/java/ai/chalk/client/GRPCClient.java, src/test/java/ai/chalk/client/TestAllClients.java, src/test/java/ai/chalk/client/TestChalkClient.java
We were incorrectly using non-grpc query hosts for the gRPC client.
Includes changes to fix test clients and responses not being closed.
=> [xs] fix grpc host

README.md, gradle.properties
=> [generated] Release 1.1.2

README.md, gradle.properties
=> [generated] Release 1.2.0

README.md, gradle.properties
=> [generated] Release 1.2.1
