- src/main/java/ai/chalk/models/OnlineQueryParams.java
- src/test/java/ai/chalk/client/TestOnlineQueryParams.java
Builder methods signatures were not the most user friendly. This PR improves upon that. Specifically, we purge all instances where we took in `Object...`, and we also change methods that add to a map to take in a map.
> Improve builder methods

- src/main/java/ai/chalk/internal/request/RequestHandler.java
The default of 1200 when using JDK 17 is too high, and the server closes the connection but our client tries to reuse the connection.
> Set keep alive to 300

- README.md
- build.gradle
Some releasing mash up means we need to release with a new version number
> bump version to 0.4.5

- src/test/java/ai/chalk/client/TestChalkClient.java
Previously we disabled because we have not set up the correct env vars. Now that we have, enable the test.
> enable e2e test

- README.md
- build.gradle
- src/main/java/ai/chalk/internal/arrow/FeatherProcessor.java
- src/main/java/ai/chalk/models/OnlineQueryResult.java
- src/test/java/ai/chalk/client/TestChalkClient.java
- src/test/java/ai/chalk/client/TestOnlineQueryParams.java
This PR builds a query input arrow table with strings that default to the type LargeUTF8 and binary data that default to the type LargeBinary
> Use LargeUTF8 and LargeBinary instead

- README.md
- build.gradle
- src/main/java/ai/chalk/client/ChalkClientImpl.java
- src/main/java/ai/chalk/internal/config/Loader.java
- src/main/java/ai/chalk/internal/config/models/SourcedConfig.java
- src/test/java/ai/chalk/internal/TestConfigLoader.java
We were failing to parse a timestamp string in chalk.yaml, but errors were not shown due to multiple issues. This PR fixes those issues:
> Fix error not showing when chalk yaml parsing fails 

- README.md
- build.gradle
- src/main/java/ai/chalk/features/Name.java
- src/main/java/ai/chalk/internal/Utils.java
- src/main/java/ai/chalk/internal/arrow/Unmarshaller.java
- src/main/java/ai/chalk/internal/codegen/Initializer.java
- src/test/java/ai/chalk/arrow/TestFeather.java
- src/test/java/ai/chalk/arrow/TestUnmarshaller.java
- src/test/java/ai/chalk/arrow/test_features/ArrowFeatures.java
- src/test/java/ai/chalk/arrow/test_features/NamedFeaturesClass.java
- src/test/java/ai/chalk/arrow/test_features/User.java
- src/test/java/ai/chalk/arrow/test_features/VanillaDataclass.java
- src/test/java/ai/chalk/arrow/test_features/VersionedFeaturesClass.java
- src/test/java/ai/chalk/arrow/test_features/_WindowedFeatures.java
- src/test/java/ai/chalk/internal/TestUtils.java
This PR supports codegen-ed features with camel-case names. Camel case names that cannot be faithfully converted into its original Python feature name will have a `Name` annotation present. This PR introduces that annotation and adds a test for its handling.
Since snake-casing snake-case field names is no-op, this change should be backwards compatible with all existing codegen-ed structs. A test is added in `TestSnakeCaseBackCompat` to ensure this.
> Support codegen with camel-cased field names [CHA-3548]

- README.md
- build.gradle
- src/main/java/ai/chalk/models/OnlineQueryParams.java
- src/test/java/ai/chalk/client/TestOnlineQueryParams.java
This PR introduces support for using FeaturesBase as an argument to `withOutputs`
> FeatureBase as output

- README.md
- build.gradle
- src/main/java/ai/chalk/client/AuthenticatedHeaderClientInterceptor.java
- src/main/java/ai/chalk/client/BuilderImpl.java
- src/main/java/ai/chalk/client/ChalkClient.java
- src/main/java/ai/chalk/client/ChalkClientImpl.java
- src/main/java/ai/chalk/client/GRPCClient.java
- src/main/java/ai/chalk/client/GrpcHeaders.java
- src/main/java/ai/chalk/client/GrpcSerializer.java
- src/main/java/ai/chalk/client/UnauthenticatedHeaderClientInterceptor.java
- src/main/java/ai/chalk/exceptions/ServerError.java
- src/main/java/ai/chalk/internal/Constants.java
- src/main/java/ai/chalk/internal/arrow/Unmarshaller.java
- src/main/java/ai/chalk/models/OnlineQueryParams.java
- src/main/java/ai/chalk/models/OnlineQueryParamsComplete.java
- src/main/java/ai/chalk/models/QueryMeta.java
- src/main/java/ai/chalk/models/ResolverException.java
- src/test/java/ai/chalk/client/TestChalkClient.java
- src/test/java/ai/chalk/client/TestGrpcClient.java
- src/test/java/ai/chalk/client/TestOnlineQueryParams.java
- src/test/java/ai/chalk/client/e2e/FraudTemplateFeatures.java
- src/test/java/ai/chalk/client/e2e/Investor.java
- src/test/java/ai/chalk/client/e2e/Series.java
- src/test/java/ai/chalk/client/e2e/User.java
Adds the onlineQuery method to GRPCClient, with supporting changes:
> GRPC Online Query

- src/main/java/ai/chalk/client/GRPCClient.java
- src/main/java/ai/chalk/client/GrpcSerializer.java
- src/main/java/ai/chalk/models/QueryMeta.java
- src/test/java/ai/chalk/client/TestGrpcClient.java
Populates GRPC online query response with a trace ID that's extracted by a metadata interceptor.
> Populate GRPC QueryMeta with trace ID

- src/main/java/ai/chalk/client/ChalkClientImpl.java
- src/main/java/ai/chalk/internal/request/models/OnlineQueryBulkResponse.java
- src/main/java/ai/chalk/internal/request/models/OnlineQueryResultFeather.java
Ensure that we free intermediate result tables when an exception occurs during response parsing.
> Plug some response parsing leaks

- src/main/java/ai/chalk/internal/Constants.java
- src/main/java/ai/chalk/internal/arrow/Unmarshaller.java
GRPC bulk query endpoint will start including more metadata columns, so java client should skip all `__chalk__` prefixes instead of just skipping `__chalk__.__metadata__` when unmarshalling table into feature classes.
> [xs] skip all __chalk__ prefixed columns [CHA-4379]

- README.md
- build.gradle
- src/main/java/ai/chalk/internal/arrow/FeatherProcessor.java
- src/test/java/ai/chalk/client/TestGrpcClient.java
- src/test/java/ai/chalk/client/TestOnlineQueryParams.java
Fixes and adds tests for specifying a list of partial nulls or a list of all nulls as inputs.
> Fix crash when serializing nulls in online query inputs [CHA-4776]

- README.md
- build.gradle
Use arrow-memory-unsafe instead of arrow-memory-netty for memory management to potentially avoid dependency issues.
> Publish tagged version that uses arrow-memory-unsafe

- .github/workflows/test.yml
- src/main/java/ai/chalk/client/AuthenticatedHeaderClientInterceptor.java
- src/main/java/ai/chalk/client/GRPCClient.java
- src/main/java/ai/chalk/client/RequestHeaderInterceptor.java
- src/test/java/ai/chalk/client/TestAllClients.java
- src/test/java/ai/chalk/client/e2e/User.java
For gRPC queries, we were previously incorrectly handling the environment ID override at the request level. Here we add a request level header interceptor so that env ID overrides are respected, and add a test.
> add request level header interceptor

- README.md
- build.gradle
We published a special debug release in #125  that made the change from `arrow-memory-netty` to `arrow-memory-unsafe`. We did not revert that change before publishing our normal netty releases, causing dependency issues for customers who expect netty. Here we revert that change.
> revert to arrow-memory-netty from unsafe

- README.md
- build.gradle
- src/main/java/ai/chalk/internal/NamespaceMemoItem.java
- src/main/java/ai/chalk/internal/Utils.java
- src/main/java/ai/chalk/internal/arrow/FeatherProcessor.java
- src/main/java/ai/chalk/internal/arrow/Unmarshaller.java
- src/main/java/ai/chalk/internal/codegen/Initializer.java
- src/test/java/ai/chalk/arrow/TestUnmarshaller.java
- src/test/java/ai/chalk/arrow/test_features/UnmarshalArrowUser.java
- src/test/java/ai/chalk/internal/TestNamespaceMemo.java
- src/test/java/ai/chalk/internal/test_features/Transaction.java
- src/test/java/ai/chalk/internal/test_features/User.java
- src/test/java/ai/chalk/internal/test_features/_WindowedFeatures_1d_30d.java
`TestBenchmarkBulkUnmarshal()` goes from ~500ms -> ~190ms
Main optimizations for unmarshalling:
Smaller fish:
TODO optimizations (separate PR)
> Make unmarshalling into structs faster

- .github/workflows/publish.yml
So that we can trigger the release action on any branch instead of having to trigger via a github release. This is helpful when the initial action fails, and we want to re-trigger on main.
> [ci] use latest tag instead of GITHUB_REF

- src/main/java/ai/chalk/client/GRPCClient.java
- src/main/java/ai/chalk/internal/bytes/BytesProducer.java
- src/main/java/ai/chalk/models/OnlineQueryParams.java
- src/test/java/ai/chalk/client/TestAllClients.java
- src/test/java/ai/chalk/client/TestChalkClient.java
- src/test/java/ai/chalk/client/TestGrpcClient.java
- src/test/java/ai/chalk/client/TestOnlineQueryParams.java
Treat query name just like outputs, and return a OnlineQueryParamsComplete accordingly
> fix named query builder

- src/main/java/ai/chalk/models/OnlineQueryParams.java
- src/test/java/ai/chalk/client/TestOnlineQueryParams.java
this ensures maximal back-compat, otherwise we can't call `withQueryName` on a `BuilderComplete`
> fix withQueryName back compat
